# Build and deploy Node.js API to Azure Web App - JRFBAttendanceAppDev

name: Build and deploy API (staging) - JRFBAttendanceAppDev

on:
  push:
    branches: [ Develop ]
  workflow_dispatch:

concurrency:
  group: api-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: npm ci, build, test (api/)
        working-directory: api
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present

      - name: Zip artifact for deployment
        run: cd api && zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # required for azure/login OIDC
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F7926B1956E3498EA0853D00621CCD14 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_254C73CFFB6A4011A8E38450F47C14BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C6F82FE3E47E41258874AC86E008A099 }}

      - name: Deploy to Azure Web App (staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'JRFBAttendanceAppDev'   # your staging Web App
          slot-name: 'Production'
          package: .
